import json

with open("aie231assgnmnt3.ipynb", "r", encoding="utf-8") as f:
    nb = json.load(f)

run5_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## RUN 5: IMPROVED ARCHITECTURE TARGETING 93%\n",
            "### Changes from Run 4:\n",
            "- 2 Conv layers per block (deeper): 32→64→128→256\n",
            "- Double Dense head: 512 → 256 → 9\n",
            "- Higher dropout: 0.25, 0.35, 0.5, 0.5\n",
            "- SGD with momentum (0.9) + CosineDecay LR (0.01 → 1e-5)\n",
            "- Label smoothing (0.1) for better calibration\n",
            "- More aggressive augmentation (+Translation)\n",
            "- 100 epochs per run, 10 runs\n",
            "- Ensemble top 3 runs for final prediction\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import datetime\n",
            "RUN5_TIMESTAMP = datetime.datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
            "RUN5_DIR = f\"./visualizations/run5_{RUN5_TIMESTAMP}\"\n",
            "os.makedirs(RUN5_DIR, exist_ok=True)\n",
            "print(f\"Run 5 outputs -> {RUN5_DIR}\")\n",
            "print(f\"Classes: {class_names}\")\n",
            "print(f\"Train: {len(train_ds)} batches, Val: {len(val_ds)} batches\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def create_model_v5(num_classes):\n",
            "    data_aug = models.Sequential([\n",
            "        layers.RandomFlip(\"horizontal_and_vertical\"),\n",
            "        layers.RandomRotation(0.3),\n",
            "        layers.RandomZoom(0.2),\n",
            "        layers.RandomBrightness(0.15),\n",
            "        layers.RandomContrast(0.15),\n",
            "        layers.RandomTranslation(0.1, 0.1),\n",
            "    ])\n",
            "    model = models.Sequential([\n",
            "        data_aug,\n",
            "        layers.Rescaling(1./255),\n",
            "        layers.Conv2D(32, (3,3), padding='same', activation='relu'),\n",
            "        layers.Conv2D(32, (3,3), padding='same', activation='relu'),\n",
            "        layers.BatchNormalization(),\n",
            "        layers.MaxPooling2D(),\n",
            "        layers.Conv2D(64, (3,3), padding='same', activation='relu'),\n",
            "        layers.Conv2D(64, (3,3), padding='same', activation='relu'),\n",
            "        layers.BatchNormalization(),\n",
            "        layers.MaxPooling2D(),\n",
            "        layers.Dropout(0.25),\n",
            "        layers.Conv2D(128, (3,3), padding='same', activation='relu'),\n",
            "        layers.Conv2D(128, (3,3), padding='same', activation='relu'),\n",
            "        layers.BatchNormalization(),\n",
            "        layers.MaxPooling2D(),\n",
            "        layers.Dropout(0.35),\n",
            "        layers.Conv2D(256, (3,3), padding='same', activation='relu'),\n",
            "        layers.Conv2D(256, (3,3), padding='same', activation='relu'),\n",
            "        layers.BatchNormalization(),\n",
            "        layers.MaxPooling2D(),\n",
            "        layers.Dropout(0.5),\n",
            "        layers.Flatten(),\n",
            "        layers.Dense(512, activation='relu'),\n",
            "        layers.BatchNormalization(),\n",
            "        layers.Dropout(0.5),\n",
            "        layers.Dense(256, activation='relu'),\n",
            "        layers.BatchNormalization(),\n",
            "        layers.Dropout(0.3),\n",
            "        layers.Dense(NUM_CLASSES, activation='softmax')\n",
            "    ])\n",
            "    return model\n",
            "\n",
            "initial_lr = 0.01\n",
            "decay_steps = 1000\n",
            "lr_schedule = tf.keras.optimizers.schedules.CosineDecay(\n",
            "    initial_learning_rate=initial_lr, decay_steps=decay_steps, alpha=1e-5/initial_lr\n",
            ")\n",
            "\n",
            "model_v5 = create_model_v5(NUM_CLASSES)\n",
            "model_v5.compile(\n",
            "    optimizer=tf.keras.optimizers.SGD(learning_rate=lr_schedule, momentum=0.9),\n",
            "    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False, label_smoothing=0.1),\n",
            "    metrics=[\"accuracy\"],\n",
            ")\n",
            "print(\"\\n--- Run 5 Architecture (Target: 93%) ---\")\n",
            "model_v5.summary()"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "NUM_RUNS_5 = 10\n",
            "EPOCHS_5 = 100\n",
            "\n",
            "best5_acc = 0\n",
            "best5_run = 0\n",
            "best5_model = None\n",
            "best5_history = None\n",
            "all5_metrics = []\n",
            "top3_models = []\n",
            "\n",
            "print(f\"{'='*60}\")\n",
            "print(f\"RUN 5: STARTING {NUM_RUNS_5} TRAINING RUNS\")\n",
            "print(f\"Architecture: Deeper 2-conv blocks, SGD+Momentum+CosineDecay\")\n",
            "print(f\"Label smoothing: 0.1 | Epochs: {EPOCHS_5} per run\")\n",
            "print(f\"Target: 93% | Current best from Run 4: 69.01%\")\n",
            "print(f\"{'='*60}\\n\")\n",
            "\n",
            "for run_num in range(1, NUM_RUNS_5 + 1):\n",
            "    print(f\"{'='*60}\")\n",
            "    print(f\"RUN 5 - RUN {run_num}/{NUM_RUNS_5}\")\n",
            "    print(f\"{'='*60}\")\n",
            "\n",
            "    m = create_model_v5(NUM_CLASSES)\n",
            "    m.compile(\n",
            "        optimizer=tf.keras.optimizers.SGD(learning_rate=lr_schedule, momentum=0.9),\n",
            "        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False, label_smoothing=0.1),\n",
            "        metrics=[\"accuracy\"],\n",
            "    )\n",
            "\n",
            "    es = callbacks.EarlyStopping(monitor=\"val_accuracy\", patience=20, restore_best_weights=True, verbose=0)\n",
            "    rlr = callbacks.ReduceLROnPlateau(monitor=\"val_loss\", factor=0.5, patience=8, min_lr=1e-6, verbose=0)\n",
            "    cp = callbacks.ModelCheckpoint(f\"{RUN5_DIR}/run{run_num}_best.keras\", monitor=\"val_accuracy\", save_best_only=True, verbose=0)\n",
            "\n",
            "    history = m.fit(train_ds, validation_data=val_ds, epochs=EPOCHS_5, callbacks=[es, rlr, cp], verbose=0)\n",
            "\n",
            "    val_acc = history.history[\"val_accuracy\"]\n",
            "    train_acc = history.history[\"accuracy\"]\n",
            "    best_val = max(val_acc)\n",
            "    best_ep = val_acc.index(best_val) + 1\n",
            "    final_val = val_acc[-1]\n",
            "    final_train = train_acc[-1]\n",
            "    epochs_run = len(val_acc)\n",
            "\n",
            "    metrics = {\"run\": run_num, \"best\": best_val, \"epoch\": best_ep, \"final_val\": final_val, \"final_train\": final_train, \"epochs\": epochs_run}\n",
            "    all5_metrics.append(metrics)\n",
            "\n",
            "    marker = \"\"\n",
            "    if best_val > best5_acc:\n",
            "        best5_acc = best_val\n",
            "        best5_run = run_num\n",
            "        best5_model = m\n",
            "        best5_history = history\n",
            "        marker = \" <<< BEST\"\n",
            "    if best_val >= 0.93:\n",
            "        marker += \" *** TARGET MET! ***\"\n",
            "\n",
            "    print(f\"  Best={best_val:.4f} (ep{best_ep})  Final={final_val:.4f}  Train={final_train:.4f}{marker}\")\n",
            "\n",
            "    top3_models.append((best_val, m))\n",
            "    top3_models.sort(key=lambda x: -x[0])\n",
            "    top3_models = top3_models[:3]\n",
            "\n",
            "    if run_num % 2 == 0 or run_num == NUM_RUNS_5:\n",
            "        print(f\"\\n>>> PROGRESS (Run {run_num}/{NUM_RUNS_5}) <<<\")\n",
            "        for m2 in all5_metrics:\n",
            "            print(f\"  Run {m2['run']}: Best={m2['best']:.4f} (ep{m2['epoch']})\")\n",
            "        print(f\"  >> Current Best: {best5_acc:.4f} (Run {best5_run})\")\n",
            "        print(f\"  >> Target: 0.93 | Gap: {0.93 - best5_acc:.4f}\")\n",
            "        print(f\"  >> Ensemble (top 3): {[x[0]:.4f for x in top3_models]}\\n\")\n",
            "\n",
            "print(f\"\\n{'='*60}\")\n",
            "print(f\"RUN 5: ALL {NUM_RUNS_5} RUNS COMPLETED\")\n",
            "print(f\"{'='*60}\")\n",
            "print(f\"Best individual: {best5_acc:.4f} (Run {best5_run})\")\n",
            "print(f\"Top 3 ensemble: {[x[0]:.4f for x in top3_models]}\")\n",
            "print(f\"Target: 0.93 | Gap: {0.93 - best5_acc:.4f}\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import numpy as np\n",
            "\n",
            "run_nums5 = [m['run'] for m in all5_metrics]\n",
            "best5_vals = [m['best'] for m in all5_metrics]\n",
            "final5_vals = [m['final_val'] for m in all5_metrics]\n",
            "\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "\n",
            "axes[0].plot(run_nums5, best5_vals, 'b-o', label='Best Val Acc', linewidth=2, markersize=8)\n",
            "axes[0].plot(run_nums5, final5_vals, 'r--s', label='Final Val Acc', linewidth=2, markersize=8)\n",
            "axes[0].axhline(y=0.93, color='g', linestyle=':', linewidth=2, label='Target: 93%')\n",
            "axes[0].set_xlabel('Run Number', fontsize=12)\n",
            "axes[0].set_ylabel('Validation Accuracy', fontsize=12)\n",
            "axes[0].set_title('Run 5: All 10 Runs', fontsize=14)\n",
            "axes[0].legend(fontsize=10)\n",
            "axes[0].grid(True, alpha=0.3)\n",
            "axes[0].set_xticks(range(1, 11))\n",
            "\n",
            "axes[1].bar(run_nums5, best5_vals, color='steelblue', alpha=0.7)\n",
            "axes[1].axhline(y=0.93, color='r', linestyle='--', linewidth=2, label='Target: 93%')\n",
            "axes[1].axhline(y=best5_acc, color='darkorange', linestyle='-', linewidth=2, label=f'Best: {best5_acc:.4f}')\n",
            "axes[1].set_xlabel('Run Number', fontsize=12)\n",
            "axes[1].set_ylabel('Best Validation Accuracy', fontsize=12)\n",
            "axes[1].set_title('Best Accuracy per Run', fontsize=14)\n",
            "axes[1].legend(fontsize=10)\n",
            "axes[1].grid(True, alpha=0.3, axis='y')\n",
            "axes[1].set_xticks(range(1, 11))\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig(f\"{RUN5_DIR}/run5_comparison.png\", dpi=150, bbox_inches=\"tight\")\n",
            "plt.show()\n",
            "\n",
            "print(f\"Best: {best5_acc:.4f} (Run {best5_run}) | Target: 0.93 | Gap: {0.93 - best5_acc:.4f}\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "acc5 = best5_history.history[\"accuracy\"]\n",
            "val_acc5 = best5_history.history[\"val_accuracy\"]\n",
            "loss5 = best5_history.history[\"loss\"]\n",
            "val_loss5 = best5_history.history[\"val_loss\"]\n",
            "\n",
            "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "\n",
            "axes[0].plot(acc5, label=\"Training Accuracy\", linewidth=2)\n",
            "axes[0].plot(val_acc5, label=\"Validation Accuracy\", linewidth=2)\n",
            "axes[0].axhline(y=0.93, color=\"g\", linestyle=\"--\", label=\"Target: 93%\")\n",
            "axes[0].set_xlabel(\"Epoch\", fontsize=12)\n",
            "axes[0].set_ylabel(\"Accuracy\", fontsize=12)\n",
            "axes[0].set_title(f\"Run 5 Accuracy Curves (Best Run: {best5_run})\", fontsize=14)\n",
            "axes[0].legend(fontsize=10)\n",
            "axes[0].grid(True, alpha=0.3)\n",
            "\n",
            "axes[1].plot(loss5, label=\"Training Loss\", linewidth=2)\n",
            "axes[1].plot(val_loss5, label=\"Validation Loss\", linewidth=2)\n",
            "axes[1].set_xlabel(\"Epoch\", fontsize=12)\n",
            "axes[1].set_ylabel(\"Loss\", fontsize=12)\n",
            "axes[1].set_title(\"Run 5 Loss Curves\", fontsize=14)\n",
            "axes[1].legend(fontsize=10)\n",
            "axes[1].grid(True, alpha=0.3)\n",
            "\n",
            "plt.tight_layout()\n",
            "plt.savefig(f\"{RUN5_DIR}/run5_accuracy_loss_curves.png\", dpi=150, bbox_inches=\"tight\")\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"\\n--- RUN 5 Classification Report (Best Model) ---\")\n",
            "y_true = np.concatenate([y for x, y in val_ds], axis=0)\n",
            "y_pred_best = np.argmax(best5_model.predict(val_ds), axis=-1)\n",
            "print(classification_report(y_true, y_pred_best, target_names=class_names))\n",
            "\n",
            "cm = confusion_matrix(y_true, y_pred_best)\n",
            "plt.figure(figsize=(12, 10))\n",
            "sns.heatmap(cm, annot=True, fmt=\"d\", cmap=\"Blues\", xticklabels=class_names, yticklabels=class_names)\n",
            "plt.xlabel(\"Predicted\", fontsize=12)\n",
            "plt.ylabel(\"Actual\", fontsize=12)\n",
            "plt.title(\"Run 5 Confusion Matrix (Best Single Model)\", fontsize=14)\n",
            "plt.tight_layout()\n",
            "plt.savefig(f\"{RUN5_DIR}/run5_confusion_matrix.png\", dpi=150, bbox_inches=\"tight\")\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"\\n--- RUN 5 Ensemble Prediction (Top 3 Models) ---\")\n",
            "all_preds = []\n",
            "for val, m in top3_models:\n",
            "    p = m.predict(val_ds, verbose=0)\n",
            "    all_preds.append(p)\n",
            "    print(f\"  Model (val_acc={val:.4f}): included\")\n",
            "avg_preds = np.mean(all_preds, axis=0)\n",
            "y_pred_ensemble = np.argmax(avg_preds, axis=-1)\n",
            "from sklearn.metrics import accuracy_score\n",
            "ensemble_acc = accuracy_score(y_true, y_pred_ensemble)\n",
            "print(f\"\\nEnsemble (top 3) Val Accuracy: {ensemble_acc:.4f}\")\n",
            "print(f\"Best Single Model Val Accuracy: {best5_acc:.4f}\")\n",
            "improvement = ensemble_acc - best5_acc\n",
            "print(f\"Ensemble Improvement: +{improvement:.4f}\")\n",
            "\n",
            "if ensemble_acc >= 0.93:\n",
            "    print(f\"\\n{'='*60}\")\n",
            "    print(f\"*** TARGET 93% MET! Ensemble accuracy: {ensemble_acc:.4f} ***\")\n",
            "    print(f\"{'='*60}\")\n",
            "else:\n",
            "    print(f\"\\nTarget: 0.93 | Ensemble Gap: {0.93 - ensemble_acc:.4f}\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "best5_model.save(f\"{RUN5_DIR}/best_model_run5.keras\")\n",
            "for i, (val, m) in enumerate(top3_models):\n",
            "    m.save(f\"{RUN5_DIR}/ensemble_model_{i+1}_{val:.4f}.keras\")\n",
            "\n",
            "run_results_5 = []\n",
            "for m2 in all5_metrics:\n",
            "    run_results_5.append(f\"Run {m2['run']}: Best={m2['best']:.4f} (ep{m2['epoch']}), Final={m2['final_val']:.4f}\")\n",
            "\n",
            "ensemble_str = f\"Ensemble (top 3): {[x[0]:.4f for x in top3_models]}\"\n",
            "result_text_5 = \"\\n\".join(run_results_5 + [ensemble_str])\n",
            "\n",
            "final_acc = max(best5_acc, ensemble_acc)\n",
            "\n",
            "run5_metrics = f\"\"\"### Run 5 (Improved Architecture - Target 93%)\n",
            "**Date**: {RUN5_TIMESTAMP}\n",
            "**Status**: {'COMPLETED - TARGET MET! :rocket:' if final_acc >= 0.93 else 'COMPLETED - Below Target'}\n",
            "\n",
            "### Configuration\n",
            "- Architecture: 2 Conv/block (32→64→128→256), Dense(512→256) head\n",
            "- Augmentation: Flip, Rotation(0.3), Zoom(0.2), Brightness(0.15), Contrast(0.15), Translation(0.1)\n",
            "- Optimizer: SGD (momentum=0.9) + CosineDecay LR (0.01 → 1e-5)\n",
            "- Loss: SparseCategoricalCrossentropy + LabelSmoothing(0.1)\n",
            "- Dropout: 0.25, 0.35, 0.5, 0.5 (conv blocks), 0.5, 0.3 (dense)\n",
            "- Epochs per run: {EPOCHS_5}\n",
            "- Number of runs: {NUM_RUNS_5}\n",
            "\n",
            "### Results (All {NUM_RUNS_5} Runs)\n",
            "{result_text_5}\n",
            "\n",
            "### Best Result\n",
            "- **Best Validation Accuracy (Single Model)**: {best5_acc:.4f} (Run {best5_run})\n",
            "- **Ensemble Accuracy (Top 3)**: {ensemble_acc:.4f}\n",
            "- **Target**: 0.93 (93%)\n",
            "- **Gap**: {0.93 - final_acc:.4f}\n",
            "- Target Met: {'YES :rocket:' if final_acc >= 0.93 else 'NO'}\n",
            "\n",
            "---\n",
            "\"\"\"\n",
            "\n",
            "with open(\"RUN_TRACKING.md\", \"a\") as f:\n",
            "    f.write(run5_metrics)\n",
            "\n",
            "print(f\"\\nRun 5 metrics saved to RUN_TRACKING.md\")\n",
            "print(f\"Visualizations saved to {RUN5_DIR}\")\n",
            "print(f\"Best model saved to {RUN5_DIR}/best_model_run5.keras\")\n",
            "print(f\"Ensemble models saved to {RUN5_DIR}/ensemble_model_*.keras\")"
        ]
    },
]

nb["cells"].extend(run5_cells)

with open("aie231assgnmnt3.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

total_cells = len(nb["cells"])
print(f"Updated notebook: {total_cells} total cells (added {len(run5_cells)} Run 5 cells)")
